name =input("What's your name?==>")
lastname =input("What's your lastname?==>")
year =input("What's your year?==>")
ID =input("What's your ID Student?==>")
print("")
print(name)
print(lastname)
print(year)
print(ID)