a =float(input("Input number[1] : "))
b =input("Input number[2] : ")
c =input("Input number[3] : ")
d =input("Input number[4] : ")
e =input("Input number[5] : ")
x = float(a)
x2 = complex(a)
y = float(b)
y2 = complex(b)
z = float(c)
z2 = complex(c)
i = float(d)
i2 = complex(d)
j = float(e)
j2 = complex(e)
print("")
print("Float of "+a + " Equal",x)
print("Complex of "+a + " Equal",x2)
print("Float of "+b + " Equal",y)
print("Complex of "+b + " Equal",y2)
print("Float of "+c + " Equal",z)
print("Complex of "+c + " Equal",z2)
print("Float of "+d + " Equal",i)
print("Complex of "+d + " Equal",i2)
print("Float of "+e + " Equal",j)
print("Complex of "+e + " Equal",j2)